Update to template 1410
Maintain backwards compatibility with stable v14 and keep cache magisk img support

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -14,29 +14,15 @@ $BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMO
 umask 022
 
 ##########################################################################################
-# Flashable update-binary preparation
+# Environment
 ##########################################################################################
-
-# DETERMINE IF PIXEL (A/B OTA) DEVICE
-ABDeviceCheck=$(cat /proc/cmdline | grep slot_suffix | wc -l)
-if [ "$ABDeviceCheck" -gt 0 ]; then
-  isABDevice=true
-  SYSTEM=/system/system
-else
-  isABDevice=false
-  SYSTEM=/system
-fi
 
 OUTFD=$2
 ZIP=$3
 
+# echo before loading util_functions									
 ui_print() {
-  if $BOOTMODE; then
-    echo "$1"
-  else
-    echo -n -e "ui_print $1\n" >> /proc/self/fd/$OUTFD
-    echo -n -e "ui_print\n" >> /proc/self/fd/$OUTFD
-  fi
+  $BOOTMODE && echo "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
 }
 
 is_mounted() {
@@ -56,49 +42,97 @@ require_new_magisk() {
   exit 1
 }
 
+mount_partitions_old() { 
+  # Check A/B slot
+  SLOT=`getprop ro.boot.slot_suffix`
+  [ -z $SLOT ] || ui_print "- A/B partition detected, current slot: $SLOT"
+  ui_print "- Mounting /system, /vendor"
+  is_mounted /system || [ -f /system/build.prop ] || mount -o ro /system 2>/dev/null
+  if ! is_mounted /system && ! [ -f /system/build.prop ]; then
+    SYSTEMBLOCK=`find /dev/block -iname system$SLOT | head -n 1`
+    mount -t ext4 -o ro $SYSTEMBLOCK /system
+  fi
+  is_mounted /system || [ -f /system/build.prop ] || abort "! Cannot mount /system"
+  cat /proc/mounts | grep -E '/dev/root|/system_root' >/dev/null && SKIP_INITRAMFS=true || SKIP_INITRAMFS=false
+  if [ -f /system/init.rc ]; then
+    SKIP_INITRAMFS=true
+    mkdir /system_root 2>/dev/null
+    mount --move /system /system_root
+    mount -o bind /system_root/system /system
+  fi
+  $SKIP_INITRAMFS && ui_print "- Device skip_initramfs detected"
+  if [ -L /system/vendor ]; then
+    # Seperate /vendor partition
+    is_mounted /vendor || mount -o ro /vendor 2>/dev/null
+    if ! is_mounted /vendor; then
+      VENDORBLOCK=`find /dev/block -iname vendor$SLOT | head -n 1`
+      mount -t ext4 -o ro $VENDORBLOCK /vendor
+    fi
+    is_mounted /vendor || abort "! Cannot mount /vendor"
+  fi
+}
+
 # Mount /data and /cache to access MAGISKBIN
 mount /data 2>/dev/null
 mount /cache 2>/dev/null
 
 # This path should work in any cases
 TMPDIR=/dev/tmp
-MOUNTPATH=/magisk
+MOUNTPATH=$TMPDIR/magisk_img
 INSTALLER=$TMPDIR/install
 if is_mounted /data; then
-  IMG=/data/magisk.img
   MAGISKBIN=/data/magisk
-  if $BOOTMODE; then
-    MOUNTPATH=/dev/magisk_merge
-    IMG=/data/magisk_merge.img
-  fi
+  $BOOTMODE && IMG=/data/magisk_merge.img || IMG=/data/magisk.img
 else
   IMG=/cache/magisk.img
   MAGISKBIN=/cache/data_bin
-  ui_print "- Data unavailable, using cache workaround"
 fi
+
+# Initial cleanup
+rm -rf $TMPDIR 2>/dev/null
+mkdir -p $INSTALLER
 
 # Utility functions must exist
 [ -f $MAGISKBIN/util_functions.sh ] || require_new_magisk
 # Load utility fuctions
 . $MAGISKBIN/util_functions.sh
+
 get_outfd
 
-rm -rf $TMPDIR 2>/dev/null
-mkdir -p $INSTALLER
-# Extract common files
-unzip -o "$ZIP" module.prop config.sh 'common/*' -d $INSTALLER 2>/dev/null
+# Check the min magisk version and mount partitions
+if [ ! -z $MAGISK_VER_CODE ] && [ $MAGISK_VER_CODE -ge 1400 ]; then
+  if [ $MAGISK_VER_CODE -ge 1410 ]; then
+    mount_partitions
+  else
+    mount_partitions_old
+  fi
+else
+  require_new_magisk
+fi
+
+$BOOTMODE && ! is_mounted /magisk && abort "! Magisk is not activated!"
+[ ! -f /system/build.prop ] && abort "! /system could not be mounted!"
+
+# Detect version and architecture
+api_level_arch_detect
+
+# You can get the Android API version from $API, the CPU architecture from $ARCH
+# Useful if you are creating Android version / platform dependent mods
+
+# We need busybox/binaries to be setup
+$BOOTMODE && boot_actions || recovery_actions
 
 ##########################################################################################
-# Prepare
+# Preparation
 ##########################################################################################
+
+# Extract common files
+unzip -o "$ZIP" module.prop config.sh 'common/*' -d $INSTALLER 2>/dev/null
 
 [ ! -f $INSTALLER/config.sh ] && abort "! Unable to extract zip file!"
 # Load configurations
 . $INSTALLER/config.sh
 
-# Check the min magisk version
-MIN_VER=`grep_prop template $INSTALLER/module.prop`
-[ ! -z $MAGISK_VER_CODE -a $MAGISK_VER_CODE -ge $MIN_VER ] || require_new_magisk
 MODID=`grep_prop id $INSTALLER/module.prop`
 MODPATH=$MOUNTPATH/$MODID
 
@@ -109,45 +143,6 @@ print_modname
 ui_print "******************************"
 ui_print "Powered by Magisk (@topjohnwu)"
 ui_print "******************************"
-
-SPACE=" "
-if [ $isABDevice == true ]; then
-  ui_print "   ! A/B OTA device detected!"
-  WRITE=rw
-  SPACE="  "
-elif [ -f /data/magisk.img ] || [ -f /cache/magisk.img ] || [ -d /magisk ]; then
-  WRITE=ro
-elif [ ! -f /data/magisk.img ] || [ ! -f /cache/magisk.img ] || [ ! -d /magisk ]; then
-  WRITE=rw
-fi
-
-ui_print "$SPACE  Mounting /system($WRITE)..."
-mount -o $WRITE /system 2>/dev/null
-ui_print "$SPACE  Mounting /vendor($WRITE)..."
-mount -o $WRITE /vendor 2>/dev/null
-
-if [ $isABDevice == true ] || [ ! -d $SYSTEM/vendor ]; then
-  VENDOR=/vendor
-else
-  VENDOR=$SYSTEM/vendor
-fi
-
-if is_mounted /data; then
-	[ ! -f /data/magisk.img ] && abort "! Magisk is not installed"
-else
-	[ ! -f /cache/magisk.img ] && abort "! Magisk is not installed"
-fi
-$BOOTMODE && ! is_mounted /magisk && abort "! Magisk is not activated!"
-[ ! -f $SYSTEM/build.prop ] && abort "! $SYSTEM could not be mounted!"
-
-# Detect version and architecture
-api_level_arch_detect
-
-# You can get the Android API version from $API, the CPU architecture from $ARCH
-# Useful if you are creating Android version / platform dependent mods
-
-# We need busybox/binaries to be setup
-$BOOTMODE && boot_actions || recovery_actions
 
 ##########################################################################################
 # Install
@@ -173,8 +168,12 @@ ui_print "- Mounting $IMG to $MOUNTPATH"
 MAGISKLOOP=`$MAGISKBIN/magisk --mountimg $IMG $MOUNTPATH`
 is_mounted $MOUNTPATH || abort "! $IMG mount failed..."
 
-if [ "$(cat $MODPATH/module.prop)" == "$(cat $INSTALLER/module.prop)" ]; then
-  ACTION="Uninstall"
+if [ -f "$MODPATH/module.prop" ]; then
+  if [ $(grep "versionCode=" $MODPATH/module.prop | sed 's/^.*=//') -ge $(grep "versionCode=" $INSTALLER/module.prop | sed 's/^.*=//') ]; then
+    ACTION="Uninstall"
+  else
+    ACTION="Install"
+  fi
 else
   ACTION="Install"
 fi
@@ -186,9 +185,11 @@ if [ "$ACTION" == "Install" ]; then
   mkdir -p $MODPATH
 
   # Copy files
-  ui_print "- Copying files"
+  ui_print "- Extracting module files"
   unzip -o "$ZIP" 'system/*' -d $MODPATH 2>/dev/null
   unzip -o "$ZIP" 'wget' -d $MODPATH 2>/dev/null
+  # Remove placeholder (people always forgot to remove it...)
+  rm -f $MODPATH/system/placeholder 2>/dev/null
 
   # Handle replace folders
   for TARGET in $REPLACE; do
@@ -221,7 +222,7 @@ if [ "$ACTION" == "Install" ]; then
 else
 
   # Uninstall module
-  ui_print "- ! Current Version of Module Detected ! Uninstalling"
+  ui_print "- ! Current or Newer Version of Module Detected ! Uninstalling -"
   rm -rf $MODPATH 2>/dev/null
   rm -rf /magisk/$MODID
 
@@ -231,7 +232,6 @@ fi
 ##########################################################################################
 
 $MAGISKBIN/magisk --umountimg $MOUNTPATH $MAGISKLOOP
-rmdir $MOUNTPATH
 
 # Shrink the image if possible
 image_size_check $IMG
@@ -242,11 +242,7 @@ if [ $curSizeM -gt $newSizeM ]; then
 fi
 
 $BOOTMODE || recovery_cleanup
-
-if [ $isABDevice == true ]; then
-  mount -o ro /system 2>/dev/null
-  mount -o ro /vendor 2>/dev/null
-fi
+rm -rf $TMPDIR
 
 ui_print "- Done"
 exit 0
